### ISSUE TITLE
Compatibility with multiple-cucumber-html-reporter

### ISSUE THREAD

**Issue by z0n** [SimitTomar/wdio-cucumber-parallel-execution#13]
Hi, I'm currently using [multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter/) with [wdio-cucumberjs-json-reporter](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter).
I want to start using wdio-cucumber-parallel-execution but keep my reporting format. This _almost_ works but I have one issue: It seems like stitching together the JSON file like described in the README works, but it also joins all test platforms in the same feature, like this (I'm running on Firefox and Chrome):
* Feature 1
  * Scenario 1
  * Scenario 1
  * Scenario 2
  * Scenario 2
  * Scenario 3
  * Scenario 3
* Feature 2 
  * Scenario 1
  * Scenario 1
...
The other reporter does it like this:
* Feature 1
  * Scenario 1
  * Scenario 2
  * Scenario 3
* Feature 1
  * Scenario 1
  * Scenario 2
  * Scenario 3
* Feature 2 
  * Scenario 1
* Feature 2 
  * Scenario 1

Metadata like browser version is displayed in the results table so it's kind of easy to read. Is there a way I can also reproduce this with wdio-cucumber-parallel-execution?

**Comment by SimitTomar** [comment]
Hi, 
The way code has been written is the way that it will stitch all the Scenarios which have the same 'Feature Description' so since **Scenario 1** of **Platform 1** and **Scenario 1** of **Platform 2** both have the same 'Feature Description', the logic puts them under the same Feature.
I am afraid, this can't be achieved with the existing implementation.
